repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        types: [ python ]
        pass_filenames: false

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy src/
        language: system
        types: [ python ]
        pass_filenames: false